[tool.poetry]
name = "hotel-finder-agent"
version = "0.1.0"
description = "An AI-powered agent for finding hotels using the Model Context Protocol (MCP) and Streamlit."
authors = ["Nilesh Gode"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"

# Core application framework
streamlit = "^1.30.0"

# AI and Agent libraries
agno = "^0.1.0"          # The agent framework being used
mcp = "^0.1.0"           # Model Context Protocol client library
# Note: Replace "*" or version numbers for 'agno' and 'mcp' 
# with the specific versions you have installed if known.

# Environment variable management
python-dotenv = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
ruff = "^0.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# This allows you to run the app using 'poetry run start'
start = "streamlit run app.py"
